language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

before_script:
    - composer self-update
    - composer install
    - if [ "$TRAVIS_PHP_VERSION" = 'hhvm' ]; then export COMPOSER_PROCESS_TIMEOUT=900; fi

script:
    - vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
